apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-demo
spec:
  selector:
    matchLabels:
      app: application-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: application-demo
    spec:
      containers:
      - name: application-demo
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080