apiVersion: v1
kind: Service
metadata:
  name: application-demo-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.206
  selector:
    app: application-demo
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80