apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeseal-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ngel-Castro/application-demo.git
    targetRevision: HEAD
    path: kubeseal
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
